feat: Add support ed25519-signature-2020 for JSONLD
cheqd/veramo pull request #3
Opened 2022-09-20 10:04 UTC by DaevMithran

Signed-off-by: DaevMithran <daevmithran1999@gmail.com>

## Fix #1003 

## What is being changed
This PR adds experimental support of Ed25519Signature2020 signature suite

## Issues faced

- The local key's publicKeyHex is different from resolved DID's publicKeyHex it fails at this [step](https://github.com/DaevMithran/veramo/blob/ed255192020-JSONLD/packages/credential-ld/src/action-handler.ts#L232)
- Getting an invalid function error at this [step](https://github.com/DaevMithran/veramo/blob/ed255192020-JSONLD/packages/credential-ld/src/suites/Ed25519Signature2020.ts#L54) . Link to the [package](https://www.npmjs.com/package/@digitalcredentials/ed25519-signature-2020)

2022-09-21 09:57 UTC, Eengineer1 commented on packages/credential-ld/src/suites/Ed25519Signature2020.ts
> +import { Ed25519VerificationKey2020, Ed25519Signature2020 } from '@digitalcredentials/ed25519-signature-2020'
@DaevMithran Please resolve this and remove `@ts-ignore`.

2022-09-21 10:02 UTC, Eengineer1 commented on packages/credential-ld/src/suites/Ed25519Signature2020.ts
> +    })
@DaevMithran Can you fix instantiations as well?
This is incorrect.
You can utilise the class structure to replace this block, as this is brought over from `Ed25519Signature2018`.

2022-09-21 10:04 UTC, Eengineer1 requested changes
@DaevMithran Needs polishing & clean-ups, but it's heading to a good direction overall.
Can you also provide a short summary on how you're testing your approach / your local setup for testing and potentially changes you're making?

Let me know when you've made the changes as well.

2022-09-22 10:15 UTC, DaevMithran commented
Hey @Eengineer1 

I have pushed changes. I was able to create a JSONLD credential after these changes

1. Change publicKeyMultibase encoding [here](https://github.com/DaevMithran/veramo/blob/ed255192020-JSONLD/packages/credential-ld/src/suites/Ed25519Signature2020.ts#L50): The publicKey should be encoded using `MULTICODEC_ED25519_PUB_HEADER = new Uint8Array([0xed, 0x01])` This should be done in the cheqd/sdk created a pull request for that [here](https://github.com/cheqd/sdk/pull/43).
2. Modified the signer's anonymous sign funciton [here](https://github.com/DaevMithran/veramo/blob/ed255192020-JSONLD/packages/credential-ld/src/suites/Ed25519Signature2020.ts#L35)
3. Declared the digitalcredenitals package modules [here](https://github.com/DaevMithran/veramo/blob/ed255192020-JSONLD/packages/credential-ld/src/module-types/jsonld/index.d.ts)
4. Added an assertion method to the didDoc [here](https://github.com/DaevMithran/veramo/blob/ed255192020-JSONLD/packages/utils/src/did-utils.ts#L161). This also needs to be done in cheqd/sdk pushed this change in the same pull request mentioned above


Further Improvements

- the signatureMap function allows only one suit for a KeyType [link](https://github.com/DaevMithran/veramo/blob/ed255192020-JSONLD/packages/credential-ld/src/ld-suite-loader.ts#L10) . Both Ed25519Signature2020 & Ed25519Signature2018 have the same KeyType: Ed25519. Need to find some solutions for that.

2022-09-22 14:57 UTC, Eengineer1 requested changes
@DaevMithran It seems the `cheqd:feat/jsonLDSupport` branch was not in sync with the respective upstream branch, resulting in a total mess of commits included with your personal changes.
I've synchronized it, so you're good to go.

Steps to resolve this:
- Switch to `cheqd` Veramo fork first (next time please do start from here, rather than your personal `DaevMithran` fork <-- this one you only control yourself, so redundant complexity).
- Carry over your changes to `feat/jsonLDSupport`.
- Target that PR to `cheqd:next`.
- Close *this* one.
- On internal approval, we can open a final PR for upstream review by targeting `veramo:next`.

Thanks!

2022-09-22 15:34 UTC, DaevMithran commented
@Eengineer1 sorry didn't notice this. Can I fork the veramo's next branch and push it in cheqd/jsonLdsupport. 

By that way it will be easier to create a pull request to veramo's next branch. I think the other commits in cheqd's next branch are irrelevant

2022-09-22 15:38 UTC, Eengineer1 commented
@Eengineer1 
> I think the other commits in cheqd's next branch are irrelevant

That's correct, but that's the exact reason for the described steps above.

Could you try following the described steps above?
It will be easier to do a thorough review as a result.

2022-09-23 05:50 UTC, closed without merging